### ISSUE TITLE
multi server

### ISSUE THREAD

**Issue by dries-c** [LegendOfMCPE/Hormones#15]
i have 2 eggwars servers

but i cant set that if 1 server is full you goes to another

now it is 
server 1 : 8
server 2 : 8

**Comment by SOF3** [comment]
What exactly happens right now?

**Comment by dries-c** [comment]
Server 1: 13
Server 2: 12

Op 28-jun.-2017 17:07 schreef "SOFe" <notifications@github.com>:

**Comment by SOF3** [comment]
I don't understand your post. You didn't describe what happened, just gave two numbers that I don't know what they are.

**Comment by SOF3** [comment]
This issue will remain closed until better elaborated.
