### ISSUE TITLE
Alt. server query returns N/A when the player count is much larger than server max player

### ISSUE THREAD

**Issue by intagaming** [LegendOfMCPE/Hormones#17]
I set up a bridge server with soft-limit of 0 player and server max player of 1. So it will always searching for the lowest player count server in the organ.
However when the player count raises pass the max player count, say 7/1, the Recommended alt. server starts to turn into N/A.
If I set up a server in that organ with 0/1, soft limit 0 like before, it always point the right server with no problem.
Basically, the soft limit must much lower than the max player in order for the balance system to be worked. And now I don't know how to set up a bridge server anymore..

I'm not gonna lie, but when I have 3 servers in the organ include this bridge one, the problem happens. When I have only 2 include the bridge, the player was transfered, but stuck with the Syncing texture pack. I did successfully transfered if one player is transfered, once at a time, but the heavy transfer seems to make all players stuck. Please help.

**Comment by intagaming** [comment]
Oi! Solution:
`if($altResult instanceof MysqlSelectResult and count($altResult->rows) === 1){`
To:
`if($altResult instanceof MysqlSelectResult and count($altResult->rows) >= 1){`
in LymphVessel.php, since it is always not return 1 row if you have >1 servers in organ, query debugged.

**Comment by SOF3** [comment]
Mind making a PR? I'll check it later. I'm busy on [Poggit `better-submit`](https://github.com/poggit/poggit/tree/better-submit) these days.

**Comment by SOF3** [comment]
Fixed in #19
