### ISSUE TITLE
add balancer bypass for /transfer'ed users.

### ISSUE THREAD

**Issue by dries-c** [LegendOfMCPE/Hormones#20]
add a permission for players to bypass the max count

**Comment by SOF3** [comment]
As I mentioned [here](https://github.com/LegendOfMCPE/Hormones/blob/a1181fb3b051c33460d092557bed8b1313321dc2/Hormones/src/Hormones/Utils/Balancer/BalancerModule.php#L65), Hormones checks the bypass immediately when the player logins, and it is highly likely that permission plugins have not yet setup player permissions yet, especially if they fetch data asynchronously. It is therefore unreliable to use permissions.

**Comment by dries-c** [comment]
not there on send

**Comment by SOF3** [comment]
?

**Comment by dries-c** [comment]
Let /transfer bypass the hormones max and not the server max

Op 13-jul.-2017 09:47 schreef "SOFe" <notifications@github.com>:

**Comment by SOF3** [comment]
@Driesboy Alright, please edit the issue to clarify.

**Comment by SOF3** [comment]
@Driesboy Then how is this related to ranks and permissions?

**Comment by dries-c** [comment]
if a player dont have the permission the hormones max will be used
if player has the permission server max will be used

**Comment by SOF3** [comment]
@Driesboy player has what permission? How is this related to /transfer, or what does "not there on send" mean?

**Comment by dries-c** [comment]
another like transfer.vip

**Comment by SOF3** [comment]
@Driesboy Can you please give a **detailed description** of what you want? I can't read minds. The name doesn't mean anything without explanation.

**Comment by dries-c** [comment]
the only thing i want is: let a player with a permission bypass playerSoftLimit but not the server max count

**Comment by dries-c** [comment]
like exemptPlayers but with permissions

**Comment by SOF3** [comment]
@Driesboy I already explained. Hormones may check the permissions **before** permission plugin sets the permission, so it may be **impossible**, or at least **unstable** to check for permissions when the player joins.

**Comment by dries-c** [comment]
But is it posible to check it on use the transfer command and not on join?

Op 13-jul.-2017 14:45 schreef "SOFe" <notifications@github.com>:

**Comment by SOF3** [comment]
@Driesboy Then what about an option that bypasses balancer whenever the player is transferred internally?

**Comment by dries-c** [comment]
yep that is what i mean

**Comment by SOF3** [comment]
@Driesboy And it has nothing to do with permissions, right? That's something I'm going to add when TransferOnly module is officially supported.

**Comment by dries-c** [comment]
i only want that if a player has permission and it has 30 softlimit, 30 players and 35 slots the player can join that server

**Comment by SOF3** [comment]
So do you want a transferred player to bypass, or a transferred player with a permission on the first server to bypass?
And are you referring to all /transfer'ed players, or just players transferred by Hormones?
I mean, it is impossible to check any permissions in the balancer. But it is possible to check it for players who are transferred internally.

**Comment by dries-c** [comment]
players transferred by hormones

**Comment by dries-c** [comment]
The only thing i want is that a player with a perm can bypass the softlimit
