### ISSUE TITLE
transfer bug

### ISSUE THREAD

**Issue by dries-c** [LegendOfMCPE/Hormones#28]
if you set alwaystransfer false
logLast is working

**Comment by dries-c** [comment]
if you set loglast later to false
players will be always teleported to there old loglast from when i disabled it

**Comment by SOF3** [comment]
This should have been caused by a typo that reads `stopTransfer` as `alwaysTransfer`.

**Comment by SOF3** [comment]
If possible, please help me test and make sure if things are fixed.

**Comment by dries-c** [comment]
going to test it tomorrow
