### ISSUE TITLE
bypass softlimit dont work

### ISSUE THREAD

**Issue by dries-c** [LegendOfMCPE/Hormones#32]

**Comment by SOF3** [comment]
Not even if their names are in the `fullExemptPlayers` list?

**Comment by dries-c** [comment]
Get the server full and try to join with the command

Op 7-aug.-2017 19:55 schreef "SOFe" <notifications@github.com>:

**Comment by SOF3** [comment]
Joining directly and joining with command have no difference, right?

**Comment by dries-c** [comment]
yep

Op 7-aug.-2017 20:22 schreef "SOFe" <notifications@github.com>:
