### ISSUE TITLE
Class missing

### ISSUE THREAD

**Issue by Wertzui123** [LegendOfMCPE/Hormones#38]
16:23:35] [Server thread/CRITICAL]: Error: "Class 'spoondetector\SpoonDetector' not found" (EXCEPTION) in "plugins/Hormones/src/Hormones/HormonesPlugin" at line 110

**Comment by SOF3** [comment]
Download the phar from Poggit. Do not download by pressing the "Download ZIP button.

**Comment by Wertzui123** [comment]
Ok
