### ISSUE TITLE
raklib blocks player for 5 seconds on transfer

### ISSUE THREAD

**Issue by dries-c** [LegendOfMCPE/Hormones#6]

**Comment by SOF3** [comment]
Please set `debug.level` to 2 in the server that the player is blocked and show the stack trace that will be displayed.

Please also provide full steps to reproduce the issue.

**Comment by dries-c** [comment]
![naamloos 2](https://cloud.githubusercontent.com/assets/15795262/26283274/40508b06-3e25-11e7-9479-9ed616d7baea.jpeg)
![naamloos3](https://cloud.githubusercontent.com/assets/15795262/26283275/437bab80-3e25-11e7-8ee8-6b672a6e23a4.jpeg)

**Comment by dries-c** [comment]
latest https://github.com/LegendOfMCPE/Hormones/releases/tag/v2.0.0-beta

**Comment by dries-c** [comment]
transfer a player to another server

**Comment by SOF3** [comment]
This seems to be an issue with PocketMine.

**Comment by SOF3** [comment]
Which method are you using to transfer player?

**Comment by dktapps** [comment]
May I ask what version of the MCPE client you are using?

**Comment by dries-c** [comment]
Direct

Op 21-mei-2017 14:34 schreef "SOFe" <notifications@github.com>:

**Comment by SOF3** [comment]
@Driesboy Direct? What do you mean? Is it something related to Hormones at all?

**Comment by SOF3** [comment]
@Driesboy Mind copying allthethings in console here?

**Comment by dries-c** [comment]
Mcpe 1.0.8

**Comment by dktapps** [comment]
That's very unusual... since the batch payload is 4-byte int instead of a variable-length integer, that looks more like a 0.15 player attempted to join your server. Could you paste the full packet hexdump?

**Comment by dries-c** [comment]
i did nothing and today its fixed with the same client
