### ISSUE TITLE
hormonesVersion should be MEDIUMINT

### ISSUE THREAD

**Issue by intagaming** [LegendOfMCPE/Hormones#8]
I'm not a pro in this type of code, but here's my experience of Hormones working in PMMP environment after some setup time:

- Default value of hormonesVersion is 65536, didn't change anything. The mysql's SMALLINT working around 0 -> 65535 (signed int I assume). Fix that to something else like MEDIUMINT and it works.
- Balance system is not working. It just not working. As below:

![image](https://cloud.githubusercontent.com/assets/16471365/26522275/d012d360-4326-11e7-9588-19db593f5564.png)

**Comment by SOF3** [comment]
For the hormonesVersion one, it's unused, so it's OK. Fixed in fab66b9 anyway.

For the "balance system is not working", please create another issue.

**Comment by SOF3** [comment]
For the transferring issue, seems that you used `127.0.0.1` for the external IP address, but according to the login log, you joined the server using `192.168.1.23`, which is a non-localhost internal IP. Try again by setting the non-localhost internal IP, or the external IP, of your server?

**Comment by SOF3** [comment]
I have a question though. Why is it `192.168.1.2` while joining but `192.168.1.23` while leaving?

**Comment by intagaming** [comment]
So I have an rig. The one is my laptop, running Windows 10. For the unable of connecting to the MCPE server on Windows 10, I use the workaround of Kaspersky Anti Virus, it changes something and I would be able to connect from my laptop (`192.168.1.23`) to my server on the laptop itself (`127.0.0.1`). The `192.168.1.2` is my phone, same wifi. I'm able to connect to both `19132` and `19133` on `192.168.1.2` and `192.168.1.23`. If I could connect to `19132`, so that I have no problem connecting to `19133` right? (Firewall disabled)

> I have a question though. Why is it 192.168.1.2 while joining but 192.168.1.23 while leaving?

Its different account. I connect to my server on my phone first, and then my laptop. Since the balance system called and cancelling the `PlayerLoginEvent`, no joining message is provided. So.. you get the point.
